// Quiz configuration constants
// Note that these depend on the API configuration generated by OTDB
// https://opentdb.com/api_config.php

const types = {
    QUESTION_COUNT: 5,
    QUESTION_CATEGORY: "",
    QUESTION_DIFFICULTY: "",

    // Question type: true/false, multiple choice, or both
    QUESTION_TYPE_TF: "boolean",
    QUESTION_TYPE_MC: "multiple",
    QUESTION_TYPE_ALL: "",

    ANSWER_TRUE: "True",
    ANSWER_FALSE: "False",

    // API format
    // e.g. https://opentdb.com/api.php?amount=5&category=15&difficulty=easy&type=multiple
    API_BASE: "https://opentdb.com/api.php?",
    API_PARAMS: {
        amount: "", // 1-50 inclusive
        category: "", // 9-32 inclusive, or null (All)
        difficulty: "", // easy | medium | hard, or null (All)
        type: "" // multiple | boolean, or null (All)
    },

    API_URL: "https://opentdb.com/api.php?amount=5&category=15", // type=multiple | boolean

    QUESTION_EXAMPLE: [
        {
            id: "lfdsjfdssdf",
            category: "Test1",
            type: "multiple",
            difficulty: "hard",
            question: "What?",
            correct_answer: "Yes to the yes",
            incorrect_answers: ["Blank","Blank2","Blank3"],
        },
        {
            id: "jkggdfkhgdf",
            category: "Test2",
            type: "boolean",
            difficulty: "medium",
            question: "Hello?",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },        
    ],

    ANSWER_EXAMPLE: [
        {
            questionId: "lfdsjfdssdf",
            answers: [
                {
                    value: "bleh",
                    id: "8543hgjsdgg",
                    correct: false,
                    selected: false
                },
                {
                    value: "agghh",
                    id: "359jksdjk",
                    correct: true,
                    selected: false
                },                
            ]
        }
    ]
}

export default types;